create scala wrapper for digdag config
civitaspo/digdag-operator-ecs_task pull request #35
Opened 2018-11-19 01:28 UTC by moc-yuto

create Scala wrapper for Digdag config for remove guava Optional

2018-11-22 04:18 UTC, civitaspo commented on src/main/scala/pro/civitaspo/digdag/plugin/ecs_task/register/EcsTaskRegisterOperator.scala
> +import com.amazonaws.services.ecs.model._
Avoid wildcard imports

2018-11-28 15:34 UTC, civitaspo commented on src/main/scala/pro/civitaspo/digdag/plugin/ecs_task/register/EcsTaskRegisterOperator.scala
> +    req.setFamily(c.get("family"))
could you follow the document order? See https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html .

2018-12-02 11:16 UTC, civitaspo requested changes
Good catch! I agree your implementation, so please apply other classes.

2018-12-14 03:54 UTC, civitaspo commented
How's this going? @moc-yuto

2018-12-14 06:17 UTC, moc-yuto commented
mmm, too many to fix...
I close this PR...
If you agree it, please implement like this.

2018-12-14 06:17 UTC, closed without merging