seems to work only when [sh] is implicitly [bash]
civitaspo/digdag-operator-ecs_task pull request #61
Opened 2019-11-12 10:21 UTC by kimurashuhei

* i've tried to use ```ecs_task.sh``` , and found that it doesn't run properly when sh is ```/bin/sh```

2019-11-18 06:02 UTC, civitaspo commented on src/main/resources/pro/civitaspo/digdag/plugin/ecs_task/sh/run.sh
> +#!/bin/bash
This shebang is not required, because this is not an executable file.

2019-11-18 06:05 UTC, civitaspo commented on src/main/scala/pro/civitaspo/digdag/plugin/ecs_task/command/S3TmpStorage.scala
> +    Seq("sh", "-c", s"aws s3 cp ${location.toString}/$mainScript ./ && /bin/bash $mainScript")
Please change `/bin/bash` to `bash` because `bash` is not necessarily located in `/bin/bash`.

2019-11-18 06:07 UTC, civitaspo requested changes
Please apply them.

2019-11-19 00:36 UTC, kimurashuhei commented
thanks for the review, i've pushed the changes, thanks.

2019-11-19 00:41 UTC, civitaspo approved these changes
Thanks a lot for your contribution.

2019-11-19 04:02 UTC, civitaspo requested changes
I am sorry to return the discussion after approval. Could you explain the details of the reason for the `it doesn't run properly when sh is /bin/sh`? I remember the reason why I used `sh`. This is for supporting several shell (`ash`, `bash`, `busybox`, `sh`), not only `bash`. When some code does not work on `sh`, I want to fix `run.sh` code.

2019-11-20 06:30 UTC, kimurashuhei commented
so, the situation i faced is for Debian based docker images.

default shell for this OS was, ```/bin/dash``` ( ```sh``` 's default symlink for Debian)

I've changed the default shell to bash for a work-around.

2019-11-20 06:36 UTC, kimurashuhei commented
i think ```pipefail``` is not supported for ```/bin/dash```

2019-11-22 07:48 UTC, civitaspo commented
ok, I got it. So, I will implement `shell` option later (maybe today or tomorrow) instead. Since the current implementation also supports `ash` and `sh`, changing to `bash` is a problem. Please wait for a while.

2019-11-22 07:48 UTC, closed without merging

2019-11-23 20:48 UTC, civitaspo commented
@kimurashuhei 0.0.14 is released! I support the `shell` option. Try it! https://github.com/civitaspo/digdag-operator-ecs_task/releases/tag/0.0.14

2019-12-12 11:43 UTC, kimurashuhei commented
thanks for following this. appreciate it. 👍